/**
 * E1 synthetic + E2 shadow packs. Tokenized refs only — no live PHI.
 */

import type { PackCaseSpec } from './types';

const COMPLETE = {
  requesting_provider: 'prov_synth_golive',
  service_or_rx: 'CPT-73721',
  place_of_service: 'office' as const,
  urgency: 'standard' as const,
  clinicals_pointer: 's3://synth/packet/golive.pdf',
  benefit_type: 'medical' as const,
};

export const SYNTHETIC_PACK: readonly PackCaseSpec[] = [
  {
    id: 'e1-happy-01',
    scenario: 'happy_path',
    label: 'Happy path MRI knee — Gravity Rail ingest',
    intake: { ...COMPLETE, external_id: 'e1-happy-01', member_ref: 'memb_synth_e1_01' },
    source: 'gravity_rail',
    criteria: 'meet',
    expected: { state: 'md_queue', criteria_result: 'meet' },
  },
  {
    id: 'e1-happy-02',
    scenario: 'happy_path',
    label: 'Happy path PT — external API ingest',
    intake: {
      ...COMPLETE,
      external_id: 'e1-happy-02',
      member_ref: 'memb_synth_e1_02',
      service_or_rx: 'CPT-97110',
    },
    source: 'external_api',
    criteria: 'meet',
    expected: { state: 'md_queue', criteria_result: 'meet' },
  },
  {
    id: 'e1-happy-03',
    scenario: 'happy_path',
    label: 'Happy path urgent — fax ingest then sign',
    intake: {
      ...COMPLETE,
      external_id: 'e1-happy-03',
      member_ref: 'memb_synth_e1_03',
      urgency: 'urgent',
      service_or_rx: 'CPT-70553',
    },
    source: 'fax_phaxio',
    criteria: 'meet',
    sign: true,
    determination: 'approve',
    expected: { state: 'determined', criteria_result: 'meet' },
  },
  {
    id: 'e1-happy-04',
    scenario: 'happy_path',
    label: 'Happy path spine create',
    intake: { ...COMPLETE, external_id: 'e1-happy-04', member_ref: 'memb_synth_e1_04' },
    source: 'spine',
    criteria: 'meet',
    expected: { state: 'md_queue', criteria_result: 'meet' },
  },
  {
    id: 'e1-happy-05',
    scenario: 'happy_path',
    label: 'Happy path pharmacy lane',
    intake: {
      ...COMPLETE,
      external_id: 'e1-happy-05',
      member_ref: 'memb_synth_e1_05',
      benefit_type: 'pharmacy',
      service_or_rx: 'NDC-0002-1433',
    },
    source: 'spine',
    criteria: 'meet',
    expected: { state: 'md_queue', criteria_result: 'meet' },
  },
  {
    id: 'e1-happy-06',
    scenario: 'happy_path',
    label: 'Happy path first-level appeal shape',
    intake: { ...COMPLETE, external_id: 'e1-happy-06', member_ref: 'memb_synth_e1_06' },
    source: 'spine',
    criteria: 'meet',
    expected: { state: 'md_queue', criteria_result: 'meet' },
  },
  {
    id: 'e1-missing-01',
    scenario: 'missing_clinicals',
    label: 'Missing clinicals pointer — R01 pause',
    intake: {
      ...COMPLETE,
      external_id: 'e1-missing-01',
      member_ref: 'memb_synth_e1_m01',
      clinicals_pointer: null,
    },
    source: 'gravity_rail',
    expected: { state: 'intake_incomplete', sla_clock: 'paused' },
  },
  {
    id: 'e1-missing-02',
    scenario: 'missing_clinicals',
    label: 'Missing member_ref — R01 pause',
    intake: {
      ...COMPLETE,
      external_id: 'e1-missing-02',
      member_ref: null,
    },
    source: 'external_api',
    expected: { state: 'intake_incomplete', sla_clock: 'paused' },
  },
  {
    id: 'e1-missing-03',
    scenario: 'missing_clinicals',
    label: 'Missing requesting provider — R01 pause',
    intake: {
      ...COMPLETE,
      external_id: 'e1-missing-03',
      member_ref: 'memb_synth_e1_m03',
      requesting_provider: null,
    },
    source: 'spine',
    expected: { state: 'intake_incomplete', sla_clock: 'paused' },
  },
  {
    id: 'e1-gray-01',
    scenario: 'gray_zone',
    label: 'Gray zone criteria — MD queue, no auto-approve',
    intake: { ...COMPLETE, external_id: 'e1-gray-01', member_ref: 'memb_synth_e1_g01' },
    source: 'spine',
    criteria: 'gray',
    expected: { state: 'md_queue', criteria_result: 'gray' },
  },
  {
    id: 'e1-gray-02',
    scenario: 'gray_zone',
    label: 'Gray zone urgent — MD must sign',
    intake: {
      ...COMPLETE,
      external_id: 'e1-gray-02',
      member_ref: 'memb_synth_e1_g02',
      urgency: 'urgent',
      service_or_rx: 'CPT-27447',
    },
    source: 'gravity_rail',
    criteria: 'gray',
    expected: { state: 'md_queue', criteria_result: 'gray' },
  },
  {
    id: 'e1-gray-03',
    scenario: 'gray_zone',
    label: 'Gray zone fail-adjacent — draft pend',
    intake: {
      ...COMPLETE,
      external_id: 'e1-gray-03',
      member_ref: 'memb_synth_e1_g03',
      service_or_rx: 'CPT-64483',
    },
    source: 'fax_phaxio',
    criteria: 'gray',
    expected: { state: 'md_queue', criteria_result: 'gray' },
  },
];

/** Live-shaped synthetic packets. MD signs. Fan-out in shadow — no member/provider final send. */
export const SHADOW_PACK: readonly PackCaseSpec[] = [
  {
    id: 'e2-shadow-01',
    scenario: 'happy_path',
    label: 'Shadow MRI — approve',
    intake: { ...COMPLETE, external_id: 'e2-shadow-01', member_ref: 'memb_synth_e2_01' },
    source: 'gravity_rail',
    criteria: 'meet',
    sign: true,
    determination: 'approve',
    expected: { state: 'fanout_complete', criteria_result: 'meet' },
  },
  {
    id: 'e2-shadow-02',
    scenario: 'happy_path',
    label: 'Shadow PT — approve',
    intake: {
      ...COMPLETE,
      external_id: 'e2-shadow-02',
      member_ref: 'memb_synth_e2_02',
      service_or_rx: 'CPT-97110',
    },
    source: 'external_api',
    criteria: 'meet',
    sign: true,
    determination: 'approve',
    expected: { state: 'fanout_complete', criteria_result: 'meet' },
  },
  {
    id: 'e2-shadow-03',
    scenario: 'gray_zone',
    label: 'Shadow gray — pend',
    intake: { ...COMPLETE, external_id: 'e2-shadow-03', member_ref: 'memb_synth_e2_03' },
    source: 'spine',
    criteria: 'gray',
    sign: true,
    determination: 'pend',
    expected: { state: 'fanout_complete', criteria_result: 'gray' },
  },
  {
    id: 'e2-shadow-04',
    scenario: 'happy_path',
    label: 'Shadow urgent — approve',
    intake: {
      ...COMPLETE,
      external_id: 'e2-shadow-04',
      member_ref: 'memb_synth_e2_04',
      urgency: 'urgent',
    },
    source: 'fax_phaxio',
    criteria: 'meet',
    sign: true,
    determination: 'approve',
    expected: { state: 'fanout_complete', criteria_result: 'meet' },
  },
  {
    id: 'e2-shadow-05',
    scenario: 'happy_path',
    label: 'Shadow deny — criteria fail',
    intake: {
      ...COMPLETE,
      external_id: 'e2-shadow-05',
      member_ref: 'memb_synth_e2_05',
      service_or_rx: 'CPT-70553',
    },
    source: 'spine',
    criteria: 'fail',
    sign: true,
    determination: 'deny',
    expected: { state: 'fanout_complete', criteria_result: 'fail' },
  },
  {
    id: 'e2-shadow-06',
    scenario: 'happy_path',
    label: 'Shadow partial',
    intake: { ...COMPLETE, external_id: 'e2-shadow-06', member_ref: 'memb_synth_e2_06' },
    source: 'spine',
    criteria: 'meet',
    sign: true,
    determination: 'partial',
    expected: { state: 'fanout_complete', criteria_result: 'meet' },
  },
  {
    id: 'e2-shadow-07',
    scenario: 'happy_path',
    label: 'Shadow pharmacy',
    intake: {
      ...COMPLETE,
      external_id: 'e2-shadow-07',
      member_ref: 'memb_synth_e2_07',
      benefit_type: 'pharmacy',
      service_or_rx: 'NDC-0002-1433',
    },
    source: 'gravity_rail',
    criteria: 'meet',
    sign: true,
    determination: 'approve',
    expected: { state: 'fanout_complete', criteria_result: 'meet' },
  },
  {
    id: 'e2-shadow-08',
    scenario: 'gray_zone',
    label: 'Shadow gray urgent — pend',
    intake: {
      ...COMPLETE,
      external_id: 'e2-shadow-08',
      member_ref: 'memb_synth_e2_08',
      urgency: 'urgent',
    },
    source: 'external_api',
    criteria: 'gray',
    sign: true,
    determination: 'pend',
    expected: { state: 'fanout_complete', criteria_result: 'gray' },
  },
  {
    id: 'e2-shadow-09',
    scenario: 'happy_path',
    label: 'Shadow expedited',
    intake: {
      ...COMPLETE,
      external_id: 'e2-shadow-09',
      member_ref: 'memb_synth_e2_09',
      urgency: 'expedited',
      service_or_rx: 'CPT-27447',
    },
    source: 'spine',
    criteria: 'meet',
    sign: true,
    determination: 'approve',
    expected: { state: 'fanout_complete', criteria_result: 'meet' },
  },
  {
    id: 'e2-shadow-10',
    scenario: 'happy_path',
    label: 'Shadow first-level appeal shape',
    intake: { ...COMPLETE, external_id: 'e2-shadow-10', member_ref: 'memb_synth_e2_10' },
    source: 'fax_phaxio',
    criteria: 'meet',
    sign: true,
    determination: 'approve',
    expected: { state: 'fanout_complete', criteria_result: 'meet' },
  },
];

export const MIN_SYNTHETIC_PACK = 10;
export const MIN_SHADOW_PACK = 10;
